
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutWrapper from "./LayoutWrapper";

// Define OpenSans font with next/font/local
const OpenSans = localFont({
  src: [
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-Light-BF63e1a1f700d0d.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-Regular-BF63e1a1f49f2a8.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-Medium-BF63e1a1f80a325.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-SemiBold-BF63e1a1f647d0a.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-Bold-BF63e1a1f2d48f8.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../../public/fonts/open-sans-font-family/OpenSans-ExtraBold-BF63e1a1f833821.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-opensans",
  display: "swap",
});

const BeVietnamPro = localFont({
  src: [
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../../public/fonts/be_vietnam_pro/ttf/BeVietnamPro-Bold.ttf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-opensans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${OpenSans.variable} ${BeVietnamPro.variable} antialiased`}>
      <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}